language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python --version

install:
  - pip install -U pip
  - pip install -U pytest pytest-cov codecov openpyxl

script:
  - pytest --cov-report term-missing --cov=fuzzytest tests/
  - codecov --token=f5104928-9f7b-4349-bc60-667d3a089011